# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79b36fbb745b9ce9feca6fd59f6d0f9e246b0bc9d4001fb243c4f488f5942b5b9aff09a1a64e8a74931c91e74301413cf2d61233752d8c9120eae7dd8bb08198

test:
  secret_key_base: a7d301e64e91ba7e844fe91f25a2a7d46583cc6d73e104357077b7cbdf5f6c973c4940bc0a37f72fb389c788383183e7c74b954863078d6eacb3b99b17d18706

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
